# This is intentionally a subset of .ci.yaml from the master branch.
enabled_branches:
  - ios-experimental

platform_properties:
  mac:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-14
      device_type: none
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }
  mac_arm64:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-14
      device_type: none
      cpu: arm64
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }
  mac_benchmark:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      device_type: none
      mac_model: "Macmini8,1"
      os: Mac-14
      tags: >
        ["devicelab", "hostonly", "mac"]
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }
  mac_x64:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-14
      device_type: none
      cpu: x86
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }
  mac_build_test:
    properties:
      contexts: >-
        [
          "osx_sdk"
        ]
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-14
      device_type: none
      cpu: x86
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }
  mac_ios:
    properties:
      contexts: >-
        [
          "osx_sdk_devicelab"
        ]
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-14|Mac-15.1
      device_os: iOS-17|iOS-18
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }
  mac_x64_ios:
    properties:
      contexts: >-
        [
          "osx_sdk_devicelab"
        ]
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "version:to_2025"}
        ]
      os: Mac-14|Mac-15.1
      cpu: x86
      device_os: iOS-17|iOS-18
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }
  mac_arm64_ios:
    properties:
      contexts: >-
        [
          "osx_sdk_devicelab"
        ]
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"},
          {"dependency": "apple_signing", "version": "none"}
        ]
      os: Mac-14|Mac-15.1
      cpu: arm64
      device_os: iOS-17|iOS-18
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }

targets:
  - name: Mac build_ios_framework_module_test
    recipe: devicelab/devicelab_drone
    timeout: 60
    properties:
      add_recipes_cq: "true"
      dependencies: >-
        [
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"}
        ]
      tags: >
        ["devicelab", "hostonly", "mac"]
      task_name: build_ios_framework_module_test
    runIf:
      - dev/**
      - packages/flutter_tools/**
      - bin/**
      - .ci.yaml
      - engine/**
      - DEPS

  - name: Mac tool_integration_tests_1_5
    recipe: flutter/flutter_drone
    timeout: 60
    properties:
      cpu: arm64
      add_recipes_cq: "true"
      dependencies: >-
        [
          {"dependency": "android_sdk", "version": "version:36v1"},
          {"dependency": "chrome_and_driver", "version": "version:125.0.6422.141"},
          {"dependency": "open_jdk", "version": "version:21"},
          {"dependency": "ruby", "version": "ruby_3.1-pod_1.13"}
        ]
      shard: tool_integration_tests
      subshard: "1_5"
      tags: >
        ["framework", "hostonly", "shard", "mac"]
      test_timeout_secs: "2700"
    runIf:
      - dev/**
      - packages/flutter_tools/**
      - bin/**
      - .ci.yaml
      - engine/**
      - DEPS
