# This is intentionally a subset of .ci.yaml from the master branch.
enabled_branches:
  - ios-experimental

platform_properties:
  mac:
    properties:
      # CIPD flutter/java/openjdk/$platform
      dependencies: >-
        [
          {"dependency": "open_jdk", "version": "version:17"}
        ]
      device_type: none
      os: Mac-14
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }

targets:
  - name: Mac mac_unopt
    recipe: engine_v2/engine_v2
    properties:
      config_name: mac_unopt
      add_recipes_cq: "true"
    timeout: 120

  - name: Mac mac_ios_engine
    recipe: engine_v2/engine_v2
    timeout: 240
    properties:
      add_recipes_cq: "true"
      release_build: "true"
      config_name: mac_ios_engine
      $flutter/osx_sdk : >-
        {
          "sdk_version": "16c5032a"
        }
    # Do not remove(https://github.com/flutter/flutter/issues/144644)
    # Scheduler will fail to get the platform
    drone_dimensions:
      - os=Mac-14
      - cpu=x86
